# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  bookifyapi:
    image: bookifyapi
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
      args:
        - configuration=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 8080:8080
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - bookify-db

  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      POSTGRES_DB: bookify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bookify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Bookify.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_HEALTH_ENABLED=true
      - KC_LOG_LEVEL=info
    volumes:
      - ./keycloak/data:/opt/keycloak/data
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/transaction-logs:/opt/keycloak/data/transaction-logs
    ports:
      - 18080:8080
