# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  bookifyapi:
    image: bookifyapi
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 8080:8080
    depends_on:
        - bookify-db

  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      POSTGRES_DB: bookify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
